name: release

on:
  workflow_dispatch:
    inputs:
      semver:
        description: 'The semver to use'
        required: true
        default: 'patch'
        type: choice
        options:
          - patch
          - minor
          - major
  pull_request:
    types: [closed]

permissions: {}

jobs:
  release:
    runs-on: ubuntu-latest
    permissions:
      contents: write
      pull-requests: write
    steps:
      - uses: actions/checkout@a37ce9120846195fa4ece8f58b268e6043cb2f26 # v3
      - uses: actions/setup-node@3235b876344d2a9aa001b8d1453c930bba69e610 # v3
        with:
          node-version-file: '.nvmrc'

      - uses: nearform/optic-release-automation-action@1f7a3866e58c58f41c7ed420e270894b0f2c089c # v3
        with:
          github-token: ${{ secrets.github_token }}
          semver: ${{ github.event.inputs.semver }}
          sync-semver-tags: 'true'
          build-command: |
            echo 'installing husky hooks..'
            npm ci
